task10
EvgenUlianov/HomeTask_1_1 pull request #11
Opened 2022-02-08 06:13 UTC by EvgenUlianov

only tests

2022-02-14 20:25 UTC, iastafyev requested changes

2022-02-14 20:25 UTC, iastafyev commented on pom.xml
> +<!--        &lt;!&ndash; https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin &ndash;&gt;-->
Видимо, я это ранее упустил: использовать комментарии вместо удаления кода - плохая практика. У нас есть git - удалённое всегда можно восстановить

2022-02-14 20:25 UTC, iastafyev commented on src/test/java/EvgenUlianov/HomeTask_1_1/Controllers/TaskControllerRestTest.java
> +class TaskControllerRestTest {
Что проверяет данный тест?

2022-02-14 20:25 UTC, iastafyev commented on src/test/java/EvgenUlianov/HomeTask_1_1/TaskManager/TaskDescriptionServiceTest.java
> +package EvgenUlianov.HomeTask_1_1.TaskManager;
Очень много дублирования кода и неудачный стиль именования тестовых методов

2022-02-15 08:05 UTC, EvgenUlianov commented on src/test/java/EvgenUlianov/HomeTask_1_1/Controllers/TaskControllerRestTest.java
> +class TaskControllerRestTest {
данный тест проверяет что одноименные вызовы в сервис выполняются один и только один раз:
покрытие кода и тесты показывают, что данное поведение гарантировано

2022-02-15 08:07 UTC, EvgenUlianov commented on pom.xml
> +<!--        &lt;!&ndash; https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin &ndash;&gt;-->
удалил мертвые куски, комментировал в процессе отладки, чтобы можно было быстро вернуться к исходному, а потом забыл удалить перед коммитом

2022-02-18 15:13 UTC, iastafyev requested changes
Всё ещё проблемы с дизайном тестов

2022-02-18 15:13 UTC, iastafyev commented on src/test/java/EvgenUlianov/HomeTask_1_1/TaskManager/TaskDescriptionServiceTest.java
> +    void toggleValidTask() {
Тест не проверяет, какое значение было сохранено, проверяет только, что было возвращено.

2022-02-18 15:13 UTC, iastafyev commented on src/test/java/EvgenUlianov/HomeTask_1_1/TaskManager/TaskDescriptionServiceTest.java
> +        Mockito.when(repository.save(expectedTaskDescription))
А это тут точно нужно?

2022-02-19 08:08 UTC, EvgenUlianov commented on src/test/java/EvgenUlianov/HomeTask_1_1/Controllers/TaskControllerRestTest.java
> +class TaskControllerRestTest {
добавил проверку имени вызванного метода, в моей архитектуре имя метода контроллера и сервиса совпадают, 
пусть это будет считаться поведением, которое мы хотим гарантировать

2022-02-19 08:39 UTC, EvgenUlianov commented on src/test/java/EvgenUlianov/HomeTask_1_1/TaskManager/TaskDescriptionServiceTest.java
> +    void tasksVoid() {
упростил тест tasksVoid

2022-02-19 08:46 UTC, EvgenUlianov commented on src/test/java/EvgenUlianov/HomeTask_1_1/TaskManager/TaskDescriptionServiceTest.java
> +    void toggleValidTask() {
toggleValidTask проверяет, что значение "actualTaskDescription.isCompleted()" = true, 
при вызове "toggle" данный тест проверяет факт переключение флага "Completed",
если переписать assert в "assertTrue(!actualTaskDescription.isCompleted());", то тест не будет проходить,
если "toggle" в каком-то из этапов обработки вызова не выполнится - то тест не будет проходить

2022-02-19 08:47 UTC, EvgenUlianov commented on src/test/java/EvgenUlianov/HomeTask_1_1/TaskManager/TaskDescriptionServiceTest.java
> +        Mockito.when(repository.save(expectedTaskDescription))
лишнее - убрал

2022-02-21 08:29 UTC, iastafyev commented on src/test/java/EvgenUlianov/HomeTask_1_1/TaskManager/TaskDescriptionServiceTest.java
> +    void toggleValidTask() {
Если в файле TaskDescriptionService.java закомментировать строку 36 (`taskRepository.save(entity.get());`) тест останется зелёным, хотя очевидно, что данное поведение некорректно

2022-02-23 19:05 UTC, EvgenUlianov commented on src/test/java/EvgenUlianov/HomeTask_1_1/TaskManager/TaskDescriptionServiceTest.java
> +    void toggleValidTask() {
добавил проверку, аналогичную по принципу проверкам в TaskControllerRestTest, но более сложную (могут быть вызваны два метода репозитория)

2022-03-17 12:42 UTC, iastafyev approved these changes

2022-04-10 18:25 UTC, merged