home tasks 4&5
EvgenUlianov/HomeTask_1_1 pull request #6
Opened 2021-11-14 14:54 UTC by EvgenUlianov

Добрый вечер!
Сделал домашние задания 4 и 5 в один заход, если так нельзя, прошу вернуть и я попытаюсь сделать все таки в два задания.

по SOLID:
вынес функцию хранения списка задач в отдельный класс "TasksDataList", и выделил его методы в отдельный интерфейс "TasksData", у нас получается абстракция, и в нужный момент надо будет всего-лишь заменить обращения к классу "TasksDataList" на класс, в котором будет реализована работа с базой данных,
для команд, определенных в функции "main" (add, print и так далее), я внес изменения, чтобы они не зависели от контекста самой функции "main": обращения к данным ("TasksData")  и к флагу завершения программы ("CompletionControl") теперь реализовано через синглтон, 

по паттернам: реализовал класс "TasksDataList" и "CompletionControl" (контролирует включение флажка для завершения программы) - синглтон,
паттерн "стратегия" у меня уже был реализован в коллекции команд, где я взял за основу стандартный функциональный интерфейс "Consumer", а его реализации добавил через лямбда -выражения,
переносить в отдельные классы не стал, иначе у меня теряется принцип единственной ответственности: если я так сделаю, я должен буду и в отдельном классе реализовать команду, и в теле функции "main" ей присваивать имя, что не совсем правильно

если надо переделать - переделаю в две отдельные задачи

2021-11-15 14:11 UTC, iastafyev commented on HomeTask_1_1.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Это файл проекта IDEA. Его в репозитории не должно быть (удалить и репозитория и добавить в .gitignore)

2021-11-15 14:12 UTC, iastafyev commented on src/main/java/General/BasicFunctions.java
> +package General;
Класс нарушает SPR (принцип единой ответственности). Эта такая "сборная солянка". Надо переделать

2021-11-15 14:13 UTC, iastafyev commented on src/main/java/General/WordDelimiter.java
> +        final char SPACE = ' ';
Подобные вещи (константы) лучше определять как статические поля класса

2021-11-15 14:15 UTC, iastafyev commented on src/main/java/Main.java
> +import General.*;
Данный класс тоже что-то вроде "сборной солянки" - надо разделить

2021-11-15 14:17 UTC, iastafyev commented on src/main/java/TaskManager/TasksDataList.java
> +        return Holder.TASKS_DATA;
Интересная реализация Singleton (это не замечание, это отметка, что сделано хорошо)

2021-11-15 14:19 UTC, iastafyev requested changes
Декомпозиция классов по SOLID пока в полной мере не удалась. Направление местами верное, но реализовано не до конца. Посмотрите разбор задания по SOLID (хотя бы начало, если хочется без подсказки задание сделать - я там рассказываю, как нужно рассуждать при принятии решения о разделении на классы)

2021-11-15 16:16 UTC, EvgenUlianov commented on HomeTask_1_1.iml
> +<?xml version="1.0" encoding="UTF-8"?>
убрал

2021-11-15 17:40 UTC, EvgenUlianov commented on src/main/java/Main.java
> +import General.*;
выделил команды в отдельный пакет, в главной функции собираю с помощью рефлексии (не знаю другого способа задать единственное место для описания команды, если я ее переселил в отдельный класс, то я либо ее явно указываю в main, либо собираю наследников от абстрактного класса)

2021-11-15 17:40 UTC, EvgenUlianov commented on src/main/java/General/BasicFunctions.java
> +package General;
убрал

2021-11-15 18:09 UTC, EvgenUlianov commented
убрал команды в отдельные классы, реализовал через абстрактный класс "Command", в главной функции команды собираю с помощью рефлексии

2021-11-17 10:06 UTC, iastafyev requested changes
Реализация хорошая, идея с использованием рефлексии мне нравится (думал и сам показать что-то такое, но потом решил, что spring успешно эти задачи решает и не стоит заморачиваться)
"Подкачал" только класс Command

2021-11-17 10:06 UTC, iastafyev commented on src/main/java/Commands/Command.java
> +public abstract class Command {
Это не паттерн "Стратегия". Это просто базовый класс, в котором нарушен принцип SPR :-(

2021-11-17 10:06 UTC, iastafyev commented on src/main/java/Commands/Command.java
> +    protected static boolean checkName (String name) {
Это метод не нужен большинству наследников. Это касается и других неабстрактных методов данного класса.

2021-11-17 10:06 UTC, iastafyev commented on src/main/java/Commands/Delete.java
> +        return "delete <идентификатор задачи>";
Отличная идея, стоить справку на основе подключаемых команд - вот это настоящая модульность

2021-11-17 19:39 UTC, EvgenUlianov commented on src/main/java/Commands/Command.java
> +    protected static boolean checkName (String name) {
функцию checkName убрал в класс TaskDescription, поскольку корректности имени - это по его части: вдруг появится проверка орфографии - он должен будет это реализовать
функцию getIndex и getNumber убрал в класс TasksDataList, поскольку это его задача следить за номером: вдруг появятся новые правила и можно будет записать только четные номера - он это сделает

функция логгирования соответственно разошлась по своим классам

2021-11-17 19:40 UTC, EvgenUlianov commented on src/main/java/Commands/Command.java
> +public abstract class Command {
исправил +заменил на интерфейс, но вернуться к лямбдам не получится, потому что теперь эти классы еще и умеют сообщать, чем они занимаются

2021-11-17 19:41 UTC, EvgenUlianov commented
внес исправления

2021-11-17 21:09 UTC, EvgenUlianov commented
вынес функциональность ввода/вывода в отдельный класс, где можно будет переопределить внешний интерфейс

2021-11-24 09:11 UTC, iastafyev approved these changes
Есть 2 замечания:
1) Требования выполнены не точно (программа выводит на печать намного больше, чем требуется по заданию, например, приглашение к вводу)
2) Нарушение SPR в классе TaskDataList

Желательно исправить, но в-целом, задание считаю выполненным.

2021-11-24 09:11 UTC, iastafyev commented on src/main/java/TaskManager/TasksDataList.java
> +    public void printTasks(Predicate<TaskDescription> predicate) {
Печать - явно лишний функционал у класс TaskDataList

2021-11-24 10:57 UTC, merged