task6: spring, singltones, reflections
EvgenUlianov/HomeTask_1_1 pull request #7
Opened 2021-12-01 18:02 UTC by EvgenUlianov

Это задание далось мне не просто (собственно это мой первый опыт по спрингу, до этого ничего не было вообще), так и не смог решить проблему с рефлексиями: когда я создаю объект сам, то в нем не работают аннотации @Autowired , поэтому я не смог сохранить рефлексию, которая у меня была в главной функции,

синглтоны все покрыл возможностями спринга, оказалось что это не сложно, но долго не мог сообразить, как это сделать

логирование покрыл возможностями спринга, думаю теперь ок,

так же выделил проверщик имени в отдельный класс - надеюсь - норм,

с подбором списка команд ерунда - мне не нравится, надо переделывать наверное, но не знаю как заменить рефлексию на возможности спринга, они наверняка где-то есть, но не знаю их, сделал тупо в лоб, плохой стиль, мне кажется

2021-12-02 06:36 UTC, iastafyev requested changes

2021-12-02 06:36 UTC, iastafyev commented on .idea/compiler.xml
> +    <bytecodeTargetLevel>
Так и осталась папка .idea. По-хорошему удалить бы её. Делается это за 2 раза: сначала надо убрать .idea из .gitignore, и удалить из репозитория (первый коммит), а потом восстановить .idea в .gitignore

2021-12-02 06:36 UTC, iastafyev commented on pom.xml
> +        <dependency>
Эта зависимость по идее уже не нужна

2021-12-02 06:36 UTC, iastafyev commented on src/main/java/EvgenUlianov/HomeTask_1_1/Commands/Add.java
> +package EvgenUlianov.HomeTask_1_1.Commands;
Раньше как-то не обращал внимания, но именование пакетов не соответствует принятым в java-мире правилам. Названия пакетов должны содержать только цифры и буквы в нижнем регистре

2021-12-02 06:36 UTC, iastafyev commented on src/main/java/EvgenUlianov/HomeTask_1_1/Commands/Command.java
> +@Configuration
Здесь эта аннотация не нужна

2021-12-02 06:36 UTC, iastafyev commented on src/main/java/EvgenUlianov/HomeTask_1_1/Commands/Add.java
> +    @Autowired
Так тоже можно, но лучше объявить поле как `final` и добавить аннотацию `@RequiredArgsContstructor`. То ли в лекции, то ли на разборе по теме объяснял почему так. И аналогично для всех других бинов

2021-12-02 06:36 UTC, iastafyev commented on src/main/java/EvgenUlianov/HomeTask_1_1/General/CompletionControl.java
> +@Service
Почему у этого бина аннотация `@Service`, а бинов-команд аннотация `@Component`?

2021-12-02 06:36 UTC, iastafyev commented on src/main/java/EvgenUlianov/HomeTask_1_1/HomeTask11Application.java
> +    private Add add;
Лучше объявить поле коллекции объектов типа `Command`, например так (использую инъекцию в поле, для понятности, лучше, как писал выше инъекция через конструктор):

`@Autorwired private List<Command> commands`

2021-12-02 06:36 UTC, iastafyev commented on src/main/java/EvgenUlianov/HomeTask_1_1/TaskManager/TaskDescription.java
> +@Slf4j
Зачем здесь `@Slf4j`?

2021-12-04 07:43 UTC, EvgenUlianov commented on pom.xml
> +        <dependency>
удалил

2021-12-04 07:44 UTC, EvgenUlianov commented on .idea/compiler.xml
> +    <bytecodeTargetLevel>
удалил

2021-12-04 07:45 UTC, EvgenUlianov commented on src/main/java/EvgenUlianov/HomeTask_1_1/Commands/Command.java
> +@Configuration
удалил

2021-12-04 08:00 UTC, EvgenUlianov commented on src/main/java/EvgenUlianov/HomeTask_1_1/General/CompletionControl.java
> +@Service
привел все к @Service

2021-12-04 08:02 UTC, EvgenUlianov commented on src/main/java/EvgenUlianov/HomeTask_1_1/TaskManager/TaskDescription.java
> +@Slf4j
осталась от прошлых версий (перестало быть нужным с переносом контроля checkName в новый класс NameController), удалил

2021-12-04 08:14 UTC, EvgenUlianov commented on src/main/java/EvgenUlianov/HomeTask_1_1/Commands/Add.java
> +    @Autowired
переделал, действительно работает, есть в разборе ДЗ на 9 минуте

2021-12-04 08:22 UTC, EvgenUlianov commented on src/main/java/EvgenUlianov/HomeTask_1_1/HomeTask11Application.java
> +    private Add add;
да, получилось, долго не мог понять как с этим работать, теперь всё получилось, проблема с рефлексией отпала сама по себе

2021-12-04 08:25 UTC, EvgenUlianov commented on src/main/java/EvgenUlianov/HomeTask_1_1/Commands/Add.java
> +package EvgenUlianov.HomeTask_1_1.Commands;
мне кажется, уже поздно переименовывать?
если надо - сообщите, я переделаю,

2021-12-04 08:28 UTC, EvgenUlianov commented
внес исправления

2021-12-06 11:46 UTC, iastafyev approved these changes

2021-12-06 11:46 UTC, iastafyev commented on src/main/java/EvgenUlianov/HomeTask_1_1/Commands/Add.java
> +package EvgenUlianov.HomeTask_1_1.Commands;
Нет, не надо, конечно. Просто на будущее.

2021-12-06 11:46 UTC, iastafyev commented on pom.xml
> +        <dependency>
А зачем зависимости от библиотек для модульного тестирования?

2021-12-06 15:53 UTC, merged