Feature/task 7
EvgenUlianov/HomeTask_1_1 pull request #8
Opened 2021-12-05 11:50 UTC by EvgenUlianov

2021-12-06 11:54 UTC, iastafyev requested changes

2021-12-06 11:54 UTC, iastafyev commented on .gitignore
> +/log.txt.2021-12-04.0.gz
.gitingore поддерживает маски

2021-12-06 11:54 UTC, iastafyev commented on README.md
> +Брузерное приложение для работы со списком задач,
По заданию требовалось реализовать REST API, а не браузерное приложение :-(

2021-12-06 11:54 UTC, iastafyev commented on src/main/java/EvgenUlianov/HomeTask_1_1/Controllers/TaskController.java
> +        commands.get("edit").accept(String.format("%s %s", Integer.toString(id), name));
Я понимаю желание сохранить старый код, но в данном случае его нужно выкинуть. Это часть задания - такое довольно часто приходится делать, поэтому нельзя жалеть свой старый код

2021-12-06 16:17 UTC, EvgenUlianov commented on .gitignore
> +/log.txt.2021-12-04.0.gz
да, спасибо, разобрался

2021-12-06 17:36 UTC, EvgenUlianov commented on README.md
> +Брузерное приложение для работы со списком задач,
готово

2021-12-08 10:01 UTC, iastafyev requested changes

2021-12-08 10:01 UTC, iastafyev commented on src/main/java/EvgenUlianov/HomeTask_1_1/TaskManager/TasksData.java
> +    List<TaskDescriptionWeb> getTasksWeb(Predicate<TaskDescription> predicate);
Смешивание слоёв получилось: транфсормация из TaskDescription в TaskDescriptionWeb выполняется и на уровне представления (в контроллере) и на уровне бизнес-логики (в реализации этого интерфейса). Надо где-то в одном месте оставить

2021-12-11 07:50 UTC, EvgenUlianov commented on src/main/java/EvgenUlianov/HomeTask_1_1/Controllers/TaskControllerRest.java
> +    @PostMapping("/delete/{id}")
поменял на DeleteMapping

2021-12-11 07:50 UTC, EvgenUlianov commented on src/main/java/EvgenUlianov/HomeTask_1_1/Controllers/TaskControllerRest.java
> +    @PostMapping("/edit/{id}")
поменял на PatchMapping

2021-12-11 08:09 UTC, EvgenUlianov commented on src/main/java/EvgenUlianov/HomeTask_1_1/TaskManager/TasksData.java
> +    List<TaskDescriptionWeb> getTasksWeb(Predicate<TaskDescription> predicate);
перенес все в TasksDataList

2021-12-14 19:39 UTC, merged